#!/usr/bin/env python
"""Run TradAI frontend (Next.js) and backend (FastAPI) concurrently.

Usage::

    python start.py

Both servers are started in development mode:

* Backend:  https://127.0.0.1:8000 (self-signed cert)  – served via ``python -m tradai.serve``
* Frontend: http://127.0.0.1:3000                         – ``npm run dev`` under ``frontend``

Press Ctrl+C to stop both processes.
"""
from __future__ import annotations

import os
import signal
import subprocess
import sys
from pathlib import Path
from typing import List
import time

ROOT = Path(__file__).resolve().parent
FRONTEND_DIR = ROOT / "frontend"

# Commands to launch (program list form for Windows compatibility)
BACKEND_CMD: List[str] = [sys.executable, "-m", "tradai.serve"]
# Use npm.cmd on Windows, npm otherwise
npm_exe = "npm.cmd" if os.name == "nt" else "npm"
# Reuse the self-signed certificate generated by the backend
CERT_DIR = Path.home() / ".tradai_ssl"
CERT_FILE = CERT_DIR / "cert.pem"
KEY_FILE = CERT_DIR / "key.pem"
# Command to start Next.js dev server (HTTP); rewrites proxy via next.config.js
FRONTEND_CMD: List[str] = [npm_exe, "run", "dev"]

backend_proc = None  # type: subprocess.Popen | None
frontend_proc = None  # type: subprocess.Popen | None


def start_process(cmd: List[str], cwd: Path | None = None, https_env: bool = False, extra_env: dict | None = None) -> subprocess.Popen:  # noqa: D401
    """Start *cmd* in *cwd* returning the Popen instance (stdout/stderr inherited)."""

    env = os.environ.copy()
    if extra_env:
        env.update(extra_env)
    # Not enabling HTTPS for frontend now; backend will run HTTP
    if https_env:
        env.update({
            "HTTPS": "true",
            "SSL_CRT_FILE": str(CERT_FILE),
            "SSL_KEY_FILE": str(KEY_FILE),
        })
    return subprocess.Popen(cmd, cwd=cwd, env=env, stdin=subprocess.PIPE)


def stop_process(proc: subprocess.Popen | None) -> None:
    """Terminate *proc* gracefully (if running)."""
    if proc and proc.poll() is None:
        try:
            proc.terminate()
            proc.wait(timeout=5)
        except Exception:
            proc.kill()


def main() -> None:  # noqa: D401
    global backend_proc, frontend_proc

    # Warn if not using project venv
    venv_path = ROOT / ".venv"
    if venv_path.exists():
        venv_bin = venv_path / ("Scripts" if os.name == "nt" else "bin")
        venv_python = venv_bin / ("python.exe" if os.name == "nt" else "python")
        running_python = Path(sys.executable).resolve()
        if venv_python.exists() and running_python != venv_python.resolve():
            print(f"[ADVERTENCIA] No estás usando el entorno virtual del proyecto: {venv_python}\nActualmente usas: {running_python}\nActiva el entorno con:\n  .venv\\Scripts\\activate   # CMD\n  .venv\\Scripts\\Activate.ps1   # PowerShell\n  source .venv/bin/activate   # Bash\n")

    # Check Python backend dependencies
    try:
        import pkg_resources
    except ImportError:
        print(
            "[ERROR] Falta 'setuptools' para comprobar dependencias. "
            "Ejecuta 'pip install setuptools' y luego 'pip install -r requirements.txt'."
        )
        sys.exit(1)

    req_path = ROOT / "requirements.txt"
    if req_path.exists():
        with open(req_path) as reqf:
            reqs = [
                line
                for line in reqf.read().splitlines()
                if line.strip() and not line.strip().startswith("#")
            ]
        try:
            pkg_resources.require(reqs)
        except (pkg_resources.DistributionNotFound, pkg_resources.VersionConflict) as e:
            print(
                f"[ERROR] Dependencias Python no satisfechas: {e}\n"
                "Ejecuta 'pip install -r requirements.txt' antes de iniciar."
            )
            sys.exit(1)

    # Check Node.js frontend dependencies
    node_modules = FRONTEND_DIR / "node_modules"
    package_json = FRONTEND_DIR / "package.json"
    if package_json.exists() and not node_modules.exists():
        print("[ERROR] Dependencias de frontend no instaladas. Ejecuta 'cd frontend && npm install' antes de iniciar.")
        sys.exit(1)
    if not package_json.exists():
        print("[ERROR] No se encontró package.json en el frontend. Verifica la estructura del proyecto.")
        sys.exit(1)

    print("Starting TradAI backend...")
    backend_proc = start_process(BACKEND_CMD, extra_env={"TRADAI_HTTP": "1"})

    print("Starting TradAI frontend (Next.js)...")
    frontend_proc = start_process(FRONTEND_CMD, cwd=FRONTEND_DIR, https_env=False)

    def _signal_handler(signum, frame):  # noqa: D401
        print("\nStopping servers... (signal", signum, ")")
        stop_process(frontend_proc)
        stop_process(backend_proc)
        sys.exit(0)

    # Handle Ctrl+C nicely
    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)

    # Wait for child processes to exit
    try:
        while True:
            # If either process dies, stop the other
            if backend_proc.poll() is not None:
                print("Backend exited, shutting down frontend.")
                stop_process(frontend_proc)
                sys.exit(backend_proc.returncode)
            if frontend_proc.poll() is not None:
                print("Frontend exited, shutting down backend.")
                stop_process(backend_proc)
                sys.exit(frontend_proc.returncode)
            # Sleep a bit to avoid busy-waiting (signal.pause not on Windows)
            time.sleep(1)
    except KeyboardInterrupt:
        _signal_handler(signal.SIGINT, None)


if __name__ == "__main__":
    main()
