#!/usr/bin/env python
"""Run TradAI frontend (Next.js) and backend (FastAPI) concurrently.

Usage::

    python start.py

Both servers are started in development mode:

* Backend:  https://127.0.0.1:8000 (self-signed cert)  – served via ``python -m tradai.serve``
* Frontend: http://127.0.0.1:3000                         – ``npm run dev`` under ``frontend``

Press Ctrl+C to stop both processes.
"""
from __future__ import annotations

import os
import signal
import subprocess
import sys
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent
FRONTEND_DIR = ROOT / "frontend"

# Commands to launch (program list form for Windows compatibility)
BACKEND_CMD: List[str] = [sys.executable, "-m", "tradai.serve"]
# Use npm.cmd on Windows, npm otherwise
npm_exe = "npm.cmd" if os.name == "nt" else "npm"
# Reuse the self-signed certificate generated by the backend
CERT_DIR = Path.home() / ".tradai_ssl"
CERT_FILE = CERT_DIR / "cert.pem"
KEY_FILE = CERT_DIR / "key.pem"
# Build command that starts Next.js in HTTPS mode with same cert
FRONTEND_CMD: List[str] = [
    npm_exe,
    "exec",
    "--",
    "next",
    "dev",
    "--https",
    "--ssl-cert",
    str(CERT_FILE),
    "--ssl-key",
    str(KEY_FILE),
]

backend_proc = None  # type: subprocess.Popen | None
frontend_proc = None  # type: subprocess.Popen | None


def start_process(cmd: List[str], cwd: Path | None = None) -> subprocess.Popen:  # noqa: D401
    """Start *cmd* in *cwd* returning the Popen instance (stdout/stderr inherited)."""

    return subprocess.Popen(cmd, cwd=cwd, stdin=subprocess.PIPE)


def stop_process(proc: subprocess.Popen | None) -> None:
    """Terminate *proc* gracefully (if running)."""
    if proc and proc.poll() is None:
        try:
            proc.terminate()
            proc.wait(timeout=5)
        except Exception:
            proc.kill()


def main() -> None:  # noqa: D401
    global backend_proc, frontend_proc

    print("Starting TradAI backend...")
    backend_proc = start_process(BACKEND_CMD)

    print("Starting TradAI frontend (Next.js)...")
    frontend_proc = start_process(FRONTEND_CMD, cwd=FRONTEND_DIR)

    def _signal_handler(signum, frame):  # noqa: D401
        print("\nStopping servers... (signal", signum, ")")
        stop_process(frontend_proc)
        stop_process(backend_proc)
        sys.exit(0)

    # Handle Ctrl+C nicely
    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)

    # Wait for child processes to exit
    try:
        while True:
            # If either process dies, stop the other
            if backend_proc.poll() is not None:
                print("Backend exited, shutting down frontend.")
                stop_process(frontend_proc)
                sys.exit(backend_proc.returncode)
            if frontend_proc.poll() is not None:
                print("Frontend exited, shutting down backend.")
                stop_process(backend_proc)
                sys.exit(frontend_proc.returncode)
            # Sleep without importing time to keep it lightweight
            signal.pause()
    except KeyboardInterrupt:
        _signal_handler(signal.SIGINT, None)


if __name__ == "__main__":
    main()
